- fix random PubSubListenTimeoutException - asyncio - Task exception was never retrieved - pubsub.py:343